# AUTO-GENERATED by `fleetflight regress --from cex-0017`. Do not edit by hand.
# Source: counterexample-0017.json  (model core-ref, sha256:9c1e4b7a0f2d)
# Found against hub-manager-ref@v0.3.1; fixed in v0.3.3 (v0.3.2 was a partial fix that still failed).
#
# Stale-command resurrection: BMS fault message lost across a hub restart, hub
# resumes the NVM-stored DISCHARGE command, inverter keeps discharging 600 ms.
import pytest

from fleetflight import load_model, replay

TRACE = [
    ("bms_fault", {}),
    ("bus_delay", {"msg": "m_fault", "extra_ms": 400}),
    ("hub_restart", {}),
    # remaining steps are non-injected and follow deterministically from the model
]


@pytest.mark.fleetflight(invariant="I1 FAULT_SHUTDOWN_BOUNDED", origin="cex-0017")
def test_cex_0017_stale_command_after_hub_restart():
    model = load_model("core-ref")
    result = replay(model, TRACE, horizon_ms=4000, seed=8841)

    assert result.invariants_ok, result.explain()
    # Stronger checks pinned from the fix, so a partial regression still fails:
    assert result.max_violation_window_ms("bms=FAULTED & inv=DISCHARGING") <= 500
    assert "m_resume" not in result.sent_messages   # hub must not resume from NVM
    assert result.state_at(700).hub == "DEGRADED"
